### ISSUE TITLE
java.lang.NullPointerException if one of the sets being updated does not exist...

### ISSUE THREAD

**Issue by wkitty42** [open744/terramaster#8]
the following is the console output of my execution of the new terramaster... i downloaded the new jar file, placed it in a directory by itself and copied over my existing terramaster.properties file... the first thing i did was to select the "Synchronize shared models" button... that ran fine... then i selected the spherical projection, zoomed in and clicked on w011n59... i got the exception below which caused me to have to kill terramaster...

> myuser@mymachine:~/TerraMaster$ java -jar terramaster.jar
getResource: jar:file:/home/myuser/TerraMaster/terramaster.jar!/gshhs_l.b
Created working copy /home/myuser/.fgfs/TerraSync.
Models/Sport/46 items (3775475 bytes)... updated to r55121.
Models/Communications/130 items (9148375 bytes)... updated to r55121.
updated to r55121.
Models/Industrial/267 items (7734502 bytes)... updated to r55121.
Models/Residential/177 items (7606527 bytes)... updated to r55121.
Models/Commercial/114 items (1658208 bytes)... updated to r55121.
Models/Transport/127 items (12436826 bytes)... updated to r55121.
Models/Airport/756 items (53415922 bytes)... updated to r55121.
Models/Aircraft/320 items (58802332 bytes)... updated to r55121.
Models/StreetFurniture/77 items (4997259 bytes)... updated to r55121.
Models/Misc/117 items (11760309 bytes)... updated to r55121.
Models/Agriculture/21 items (1392987 bytes)... updated to r55121.
Models/Military/179 items (10925509 bytes)... updated to r55121.
Models/Boundaries/104 items (4356630 bytes)... updated to r55121.
Models/Power/130 items (8374449 bytes)... updated to r55121.
Models/Maritime/288 items (41189044 bytes)... updated to r55121.
Models/Fauna/14 items (742315 bytes)... updated to r55121.
updated to r55121.
Models/Trees/123 items (5219942 bytes)... updated to r55121.
Models/Effects/39 items (103197 bytes)... updated to r55121.
sync w020n50/w011n59... updated to r55121.
Exception in thread "Thread-1" java.lang.NullPointerException
        at Svn.findAirports(Svn.java:196)
        at Svn.checkout(Svn.java:172)
        at Svn.run(Svn.java:365)

i restarted terramaster at this point and tried the same block again  with the same results...

> myuser@mymachine:~/TerraMaster$ java -jar terramaster.jar
getResource: jar:file:/home/myuser/TerraMaster/terramaster.jar!/gshhs_l.b
sync w020n50/w011n59... updated to r55121.
Exception in thread "Thread-1" java.lang.NullPointerException
        at Svn.findAirports(Svn.java:196)
        at Svn.checkout(Svn.java:172)
        at Svn.run(Svn.java:365)

third time is the charm? nope :( 

> myuser@mymachine:~/TerraMaster$ java -jar terramaster.jar
getResource: jar:file:/home/myuser/TerraMaster/terramaster.jar!/gshhs_l.b
sync w020n50/w011n59... updated to r55121.
Exception in thread "Thread-1" java.lang.NullPointerException
        at Svn.findAirports(Svn.java:196)
        at Svn.checkout(Svn.java:172)
        at Svn.run(Svn.java:365)

here i tried a different area that does contain terrain and airports... it worked... until it got to a block without an airport :( 

> myuser@mymachine:~/TerraMaster$ java -jar terramaster.jar
getResource: jar:file:/home/myuser/TerraMaster/terramaster.jar!/gshhs_l.b
sync w020n50/w011n54... Terrain/w020n50/w011n54/8 items (313185 bytes)... updated to r55121.
Airports/E/I/B//7 items (2106 bytes)... updated to r55121.
Objects/w020n50/w011n54/2 items (91 bytes)... updated to r55121.
sync w020n50/w011n53... Terrain/w020n50/w011n53/19 items (1008547 bytes)... updated to r55121.
Airports/E/I/C//15 items (5677 bytes)... updated to r55121.
Airports/E/I/I//9 items (2814 bytes)... updated to r55121.
Objects/w020n50/w011n53/5 items (131681 bytes)... updated to r55121.
sync w020n50/w011n52... updated to r55121.
Exception in thread "Thread-1" java.lang.NullPointerException
        at Svn.syncAirports(Svn.java:213)
        at Svn.checkout(Svn.java:176)
        at Svn.run(Svn.java:365)

at this point, i don't know what to do other than to file this issue report... i have the entire world and would love to easily be able to update it with one button instead of having to select broad swaths of an area and update that... by the same token, it would be nice to have one button to update just the areas one may already have...

**Comment by open744** [comment]
Thanks for the detailed report. I will post the fix shortly.

BTW it looks like you're on Linux or equivalent. You can update your entire scenery directory tree with a single command,
```
svn update /home/myuser/.fgfs/TerraSync
```
This will fetch the latest scenery for tiles that already exist in your collection.

I'll think about adding yet another button to do this :-)

**Comment by wkitty42** [comment]
@open744 : yes, i'm running kubuntu 14.04... i tried the svn update command you gave... i was unaware of it... it looks like it only worked on the base TerraSync directory... so i chose one of the hundreds of Terrain directories and was told that the meta data format was too old... v10 but my svn wants v31... running "svn upgrade" would fix that but i don't want to muck things up for TerraMaster since it is what placed the .svn directories in trees in the first place... the TerraSync in the sim doesn't use .svn directories... if i do the "svn upgrade" it will prevent older svn clients from working... does the new TerraMaster use the new svn client stuff?

maybe we should take this private but i'm not sure how :(

**Comment by open744** [comment]
Go ahead and do the 'svn upgrade' -- that's what I did on my own collection too :-)

The old TerraMaster made .svn directories all over the place, and I realised that's wrong. There should be just one .svn at the base of the scenery tree. I suspect this is what TerraSync does.

Yes TerraMaster v1.0 uses a single base.

You might realise sooner or later that the 'svn update' command at the base of the tree may not update all the subdirectories which have the .svn. If it becomes too messy, I suggest deleting the lot and start all over. (Alternately, just delete all the .svn directories, using a command like

```
find /home/myuser/.fgfs/TerraSync -name .svn | xargs rm -rf
```
#### CAUTION! Test it on a subdirectory first before running it at the base of scenery tree!

**Comment by wkitty42** [comment]
i ran a few tests first... i found that i had to run the find command on ~/.fgfs/TerraSync/Terrain and ~/.fgfs/TerraSync/Objects because otherwise it found the new .svn in the TerraSync directory...

i'm going to try the updates again with the new v1.1 and see how it all goes ;) 

FWIW: there were 32188 .svn directories in Terrain and 5772 in Objects...
